- lib/README.md
- lib/pattern/direct-messaging-service/README.md
- lib/pattern/fhir-explorer/README.md
- src/content/patterns/en/direct-messaging-service.md
Fixed issue with download link
> fix:  incorrect download link in the Direct Message README #5

- lib/pattern/direct-messaging-service/README.md
> chore: modify readme with latest changes #5

- lib/pattern/direct-messaging-service/package_sql_test.ts
- lib/pattern/lectio/README.md
> feat: migrate lectio pattern #5

- lib/service/diabetes-research-hub/README.md
- lib/service/diabetes-research-hub/drhctl.ts
- modify the README.md based on the automation script  
- make changes for executing automation script within repository
> docs(update): make modifications in  README.md 

- lib/service/diabetes-research-hub/cookbook/different-patient-column-names.sql
- lib/service/diabetes-research-hub/cookbook/sample-id-generation.sql
- added cookbook files with SQL examples
> add: add sample sql help files #29

- lib/service/diabetes-research-hub/combined-cgm-tracing-generator.ts
- lib/service/diabetes-research-hub/package.sql.ts
- lib/service/diabetes-research-hub/stateless.sql
- refactor the db views
- modify in the package
- add a new generator class
> add: add a generator file

- lib/service/diabetes-research-hub/README.md
- lib/service/diabetes-research-hub/combined-cgm-tracing-generator.ts
- lib/service/diabetes-research-hub/orchestration/deidentification-orchestration.sql
- lib/service/diabetes-research-hub/orchestration/stateless-orchestration.sql
- lib/service/diabetes-research-hub/orchestration/vv-orchestration.sql
- lib/service/diabetes-research-hub/package.sql.ts
- combined view generator
- export and invoke 
- metrics sql
- embed in package.sql
> add: metrics queries sql #29

- lib/service/diabetes-research-hub/combined-cgm-tracing-generator.ts
- lib/service/diabetes-research-hub/drhctl.ts
- rectify sqlite query script
- access sql directly through surveilr.com url
> update: rectify view sql and automation script #29

- lib/pattern/direct-messaging-service/tap.sql.ts
Added tap test in direct messaging service
> feat: add tap test in pattern #44

- lib/service/diabetes-research-hub/drhctl.ts
- modify the automation script to have the latest version import
> update: change version for remote execution #29

- lib/service/diabetes-research-hub/drhctl.ts
- lib/service/diabetes-research-hub/package.sql.ts
- remove the execution of metrics SQL which contains SQRT function(surveilr shell fails in remote)v28.0
> update: avoid metrics sql from package #29

- lib/std/web-ui-content/shell.ts
> chore: update favicon

- lib/std/web-ui-content/shell.ts
> fix: fav icon image

- lib/pattern/direct-messaging-service/tap.sql.ts
- lib/std/notebook/tap.ts
Modified the base file and tap test file
> Modify tap.ts file to avoid code duplication

- lib/service/diabetes-research-hub/dataset-specific-package/anderson.sql.ts
- lib/service/diabetes-research-hub/dataset-specific-package/dclp1-uva-study.sql.ts
- lib/service/diabetes-research-hub/dataset-specific-package/detrended-analysis.sql.ts
- lib/service/diabetes-research-hub/metrics-explanation-dml.sql
- A DDL, DML SQL along with a DB view for content retrieval has been prepared and the SQL is fetched and executed in each Dataset-specific package.
> feat: implement the metrics explanations DDL and DML for hover menu #29

- lib/std/notebook/sqlpage.ts
- lib/std/web-ui-content/uniform-resource.ts
Resolved issues with pagination URL parameters in renderSimpleMarkdown to ensure accurate query handling and navigation in SQLPage output.
> fix: pagintion url params #20

- lib/std/web-ui-content/uniform-resource.ts
This PR introduces a new IMAP detail page within the Web UI for the Uniform Resource system. Key features include:
- **IMAP Detail View**: Displays detailed information about individual IMAP resources ingested from various mail sources, providing easy access to email content directly in the Web UI.
- **Structured Email Display**: Organized view of emails with metadata and content to streamline user access.
- **Improved Navigation**: Simplifies locating and viewing specific emails within the Uniform Resource system.
> feat: add uniform resource imap detail #20

- lib/pattern/compliance-explorer/.gitignore
- lib/pattern/compliance-explorer/README.md
- lib/pattern/compliance-explorer/deps.ts
- lib/pattern/compliance-explorer/package.sql.ts
- lib/pattern/compliance-explorer/stateful.sql
- lib/pattern/compliance-explorer/stateless.sql
Created a new pattern for the compliance explorer to facilitate collecting SCF controls using `Surveilr`.The Secure Controls Framework (SCF) provides a set of cybersecurity and privacy requirements to help organizations meet regulatory, statutory, and contractual compliance. This pattern enables listing Control Regimes, the controls within each regime, and a detailed control view.
> New pattern for compliance explorer to ingest SCF controls

- .commitlintrc.cjs
- .husky/commit-msg
- .husky/pre-commit
- package.json
- pnpm-lock.yaml
This PR introduces Husky to enforce consistent and proper commit message formats across the project.
- Configured Husky to run a commit-msg hook using Commitlint to ensure commit messages follow the conventional commit format (e.g., `feat`, `fix`, `chore`).
- Added `.commitlintrc` file to define the commit message rules.
- This helps maintain a clean and meaningful Git history, making it easier to track changes and understand the purpose of each commit.
Please ensure your commit messages follow the new format going forward.
> Add Husky pre-commit hook

- lib/pattern/content-assembler/package.sql.ts
- lib/pattern/content-assembler/stateful.sql
- lib/pattern/content-assembler/stateless.sql
This PR introduces a feature to generate a filtered list of URLs specifically for periodicals.
> feat: periodical filtered url list #44

- lib/pattern/content-assembler/package.sql.ts
- lib/pattern/content-assembler/stateful.sql
- lib/pattern/content-assembler/stateless.sql
Listed all removed anchors under the subject.
> feat: removed anchor list #20

- lib/std/web-ui-content/uniform-resource.ts
This PR implements the integration of the graph and edge tables to enhance the functionality for fetching and managing IMAP data.
> feat: integrated grapha nad edge tables to fetch imap data #20

- lib/pattern/content-assembler/package.sql.ts
- lib/pattern/content-assembler/stateful.sql
This pull request introduces the integration of graph and edge tables to retrieve and structure content assembler data efficiently. The changes allow for better organization and retrieval of data across multiple components within the content assembler.
> feat: integrated graph and edge tables to fetch content assembler data #20

- lib/README.md
- lib/universal/reverse-proxy-simulate.ts
Added the file and  updated readme
> chore: add reverse proxy file for local reverse proxy testing

- lib/pattern/direct-messaging-service/package.sql.ts
- lib/std/notebook/sqlpage.ts
- lib/std/web-ui-content/console.ts
- lib/std/web-ui-content/orchestration.ts
- lib/std/web-ui-content/shell.ts
- lib/std/web-ui-content/uniform-resource.ts
Updated files resolve issues with relative URLs when using Nginx as a reverse proxy.
> chore: fix URL issue with Nginx reverse proxy

- lib/pattern/direct-messaging-service/package.sql.ts
- lib/std/notebook/sqlpage.ts
Fixed issue with email detail url redirection
> fix: issue with url #125

- lib/std/notebook/sqlpage.ts
- support/deploy/omnibus-rssd.dockerfile
> added container code

- lib/pattern/direct-messaging-service/package.sql.ts
- lib/std/notebook/sqlpage.ts
- lib/std/web-ui-content/console.ts
- lib/std/web-ui-content/docs.ts
- lib/std/web-ui-content/orchestration.ts
- lib/std/web-ui-content/shell.ts
- lib/std/web-ui-content/uniform-resource.ts
modified the parent path of package
> modify parent pathe

- lib/pattern/compliance-explorer/package.sql.ts
- lib/pattern/site-quality-explorer/package.sql.ts
This pull request addresses the issue with Nginx deployment by converting all relative URLs in the application to absolute URLs. The changes include:
- Updating link URLs to use absolute paths.
- Modifying redirect URLs to ensure they work with the Nginx server configuration.
- Adjusting breadcrumb URLs to follow the absolute URL format.
These updates ensure the application functions correctly in the deployed environment, resolving issues caused by Nginx's handling of relative URLs.
> fix: resolve Nginx deployment issue by converting pattern URLs to absolute URLs

- lib/pattern/site-quality-explorer/eg.surveilr.com-prepare.ts
This pull request introduces the following updates:
**SQL Package Installation:**
Added the necessary SQL package installation as part of the prepare statements for the Site Quality Explorer (SQE) pattern.
> chore: Add SQL package extension to prepare statements for SQE pattern #125

- lib/pattern/compliance-explorer/package.sql.ts
- lib/pattern/site-quality-explorer/package.sql.ts
This pull request addresses the following issue:
**1. Fixed URL Not Found Issue in Patterns**
Corrected invalid or broken URLs in patterns to ensure seamless resource loading and availability.
Adjusted the logic to validate and handle pattern URLs dynamically to prevent similar issues in the future.
> fix: correct the URLs not found issue in patterns

- lib/pattern/content-assembler/package.sql.ts
This commit introduces a dynamic title feature for the Content Assembler web UI.
> feat: content assembler title change #125

- lib/pattern/direct-messaging-service/README.md
- lib/pattern/direct-messaging-service/eg.surveilr.com-prepare.ts
- lib/pattern/direct-messaging-service/package.sql.ts
- lib/pattern/fhir-explorer/README.md
- lib/pattern/fhir-explorer/eg.surveilr.com-prepare.ts
- lib/pattern/fhir-explorer/package.sql.ts
Modified the prepared file with deno dax
> update web UI contents and title.  

- lib/pattern/content-assembler/package.sql.ts
- lib/pattern/content-assembler/stateful.sql
- lib/pattern/content-assembler/stateless.sql
This PR introduces a new feature that displays a list of error links to enhance the application's debugging and navigation experience.
> feat: added error link list #20

- lib/std/web-ui-content/docs.ts
This pull request addresses the issue where the breadcrumb for document function details was not displaying correctly.
> fix: corrected doc function detail breadcrumb #20

- lib/std/web-ui-content/docs.ts
This PR addresses updates and fixes to the function web UI.
> fix: function web ui update #20

- lib/std/web-ui-content/console.ts
This PR addresses the issue with the content view display, ensuring that it renders correctly as expected.
> fix: content view display #20

- lib/pattern/compliance-explorer/package.sql.ts
- lib/pattern/direct-messaging-service/package.sql.ts
- lib/pattern/fhir-explorer/package.sql.ts
- lib/pattern/info-assurance-controls/package.sql.ts
- lib/pattern/info-assurance-policies/package.sql.ts
- lib/pattern/info-assurance/package.sql.ts
- lib/pattern/infra-assurance/package.sql.ts
- lib/pattern/infra-audit/package.sql.ts
- lib/pattern/site-quality-explorer/package.sql.ts
- lib/std/package.sql.ts
This PR resolves an issue affecting the console info schema where uniform resource views were not correctly handled across all patterns. The fix ensures consistent and accurate data representation for all uniform resource view patterns in the console info schema.
> fix: console info schema uniform resource view issue for all pattern #20

- lib/pattern/linkedin-explorer/README.md
This PR introduces a comprehensive README file detailing the workflow for creating and managing the resource-surveillance.sqlite.db database using exported LinkedIn data. The README includes step-by-step instructions, code explanations, and usage guidelines to streamline the process for users and developers.
> feat: add readme file #247

- lib/service/fleetfolio/README.md
This update enhances the README with detailed instructions for setting up the Surveilr Web UI, running in watch mode, and reloading SQL changes automatically. It also includes steps for executing tests using Deno, ensuring smooth development and debugging.
> update README with WebUI setup, auto-reloading SQL, and test instructions

- lib/service/fleetfolio/README.md
- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateless.sql
This update introduces the boundary list sourced from the assurance model.
> feat: boundary list from assurance #355

- lib/service/fleetfolio/README.md
- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateless.sql
This PR introduces the Parent Boundary List, enhancing hierarchical structure handling within the system.
> feat: parent boundary list #17

- lib/service/fleetfolio/package.sql.ts
This PR introduces the implementation of the Server Detail feature, providing detailed information about a specific server in the system.
> feat: Server detail  #17

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateless.sql
Listed all available disk space of assets (servers) using OS query MS data.
> feat: list available disk space of assets using os query MS data

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateless.sql
Updated UI for Boundary asset listing and detail pages to align with Fleet design standards.
> feat: boundry asset listing and detail #355

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateless.sql
Implemented a feature to list containers of the asset.
> feat: listed container of asstet #355

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateless.sql
Added a condition to filter results in the view creation by specifying `WHERE uri="osquery-ms:query-result"`.
> fix: added uri in container view #355

- lib/pattern/osquery-ms/queries.sql.ts
This PR enhances the existing Docker container query by including the state and image_id fields.
> feat : add state and image_id in docker container query #355

- lib/pattern/osquery-ms/queries.sql.ts
This PR enhances the existing Docker container query by including the created field.
> feat : add created in docker container query #355

- lib/pattern/osquery-ms/queries.sql.ts
This PR enhances the process query by including the user ID (uid) field.
> feat : add user id  in process query #355

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateful.sql
- lib/service/fleetfolio/stateless.sql
This PR updates the naming convention of newly created tables by adding the ur_transform_ prefix.
> refactor: added ur_transform_ prefix to created tables #355

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateful.sql
- lib/service/fleetfolio/stateless.sql
This update integrates AWS resource details into FleetFolio, enhancing visibility into cloud infrastructure directly within the platform.
> feat: add aws resource details integration to fleetfolio #355

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateful.sql
- lib/service/fleetfolio/stateless.sql
This PR introduces support for AWS S3 Buckets in Fleetfolio, enabling visibility into S3 storage assets across AWS accounts.
> feat: add aws s3 bucket to fleetfolio #355

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateful.sql
- lib/service/fleetfolio/stateless.sql
This PR adds functionality to list AWS Virtual Private Clouds (VPCs) within the Fleetfolio application. It enables the system to retrieve and display existing VPCs from the connected AWS account.
> feat: add aws vpc fleetfolio #355

- lib/assurance/orchestration_md.ts
- lib/service/diabetes-research-hub/datasets-transformed-archive/study-2/README.md
- lib/service/diabetes-research-hub/datasets-transformed-archive/study-2/markdown-with-frontmatter.md
test for markdown transformation to json
> test(tools): Test for Tranform Markdown

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateful.sql
- lib/service/fleetfolio/stateless.sql
This PR introduces support for tracking and displaying AWS daily cost details.
> feat: add aws daily cost detail #355

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateless.sql
This pull request introduces the Expected Asset Service, which will be responsible for managing and validating expected asset data within the system.
> feat: add expected asset service  #355

- lib/pattern/osquery-ms/stateful.sql
- lib/service/fleetfolio/stateful.sql
- lib/service/fleetfolio/stateless.sql
This PR introduces a change to the view logic by adding a new field query_uri, which is mapped from the existing uri value. This enhancement enables the view to correctly fetch and reference the source based on the query_uri.
> feat: add uri as query_uri to fetch source #355

- lib/service/fleetfolio/package.sql.ts
- lib/service/fleetfolio/stateful.sql
- lib/service/fleetfolio/stateless.sql
This PR introduces the following enhancements:
**Process Query Enhancements**
> Added start_date and state fields to the process query.
> Updated the corresponding views to display these new fields.
**Asset Module Improvements**
> Implemented multiple logical boundaries in the asset listing and asset detail views for better data segmentation and clarity.
> feat: add more fields to process view #25

- lib/pattern/osquery-ms/queries.sql.ts
This PR introduces a new set of osquery-based evidence collection queries aligned with multiple compliance controls, focusing on network monitoring, antivirus detection, asset classification, and encrypted storage validation.
1. **VPN and SSH Process Monitoring**
- Detects running VPN-related (e.g., OpenVPN) and SSH daemon (sshd) processes.
2. **Firewall Rules (iptables)**
- Lists detailed firewall rules to support network-level monitoring.
3. **SFTP/FTPS Configuration Checks**
- Detects active SFTP/FTPS processes and validates listening ports for encrypted file transfers.
4. **Antivirus Configurations**
- Identifies antivirus services across platforms (ClamAV, Sophos, McAfee, Defender, etc.).
5. **Confidential Service Discovery**
- Identifies running database and web server processes …
> feat: add queries for vpn, sftp, antivirus, confidential services, and ebs encryption checks #355

- lib/service/fleetfolio/README.md
- lib/service/qualityfolio/README.md
- lib/std/web-ui-content/console.ts
This PR introduces a new **Behavior Configuration** section to the console menu and significantly enhances the README documentation for both Qualityfolio and Fleetfolio services.
- **New Behavior Configuration Section**: Added comprehensive behavior management interface under the console menu
- **Behavior Detail Pages**: Detailed view of behavior configurations including JSON configuration and governance settings
- **Interactive Features**: Pagination, search, and filtering capabilities for behavior management
- **Summary Cards**: Visual overview of total behaviors, active devices, and behavior types
- **Structured Getting Started Guide**: Step-by-step workflow from setup to web UI launch
- **Enhanced Feature Documentation**: Comprehensive overview of web UI capabilities including …
> feat: add Behavior Configuration to console menu and enhance readme documentation #355

- lib/service/qualityfolio/package.sql.ts
Enhanced the test-detail.sql page with outer accordion containers to improve content organization and visual hierarchy while maintaining complete backward compatibility and preserving all existing functionality.
- **Wrapper Added**: Outer accordion container with title "Test Case Details"
- **Content Preserved**: Existing card component with all markdown formatting maintained
- **Data Integrity**: All SQL queries and data display logic unchanged
- **Functionality**: Original card behavior and styling completely preserved
- **Wrapper Added**: Outer accordion container with title "Test Execution Data"
- **Content Preserved**: Complete tab system (Actual Result, Test Run, Bug Report) maintained
- **Tab Functionality**: All tab navigation, switching, and URL parameters preserved
- …
> feat: add outer accordion containers to test-detail.sql for improved organization #355

- lib/service/qualityfolio/package.sql.ts
- lib/service/qualityfolio/stateless.sql
This PR implements comprehensive TAP (Test Anything Protocol) test result views for QualityFolio, enabling dynamic parsing and display of TAP files with drill-down capabilities from file summaries to individual test cases.
- **Dynamic Filename Extraction**: Replaces hardcoded patterns with universal filename parsing
- **Dynamic Test Plan Parsing**: Extracts test plan numbers (e.g., "1..N") from any TAP content
- **Full Content Access**: Uses `ur.content` directly for complete TAP file processing
- **Summary Statistics**: Provides file-level metrics (total tests, pass rates, status)
- **Real-time TAP Parsing**: Uses recursive CTEs to split TAP content line by line
- **Individual Test Extraction**: Parses test numbers, status, case IDs, and descriptions
- **Universal Format Support**: …
> feat: implement dynamic TAP test result views for qualityfolio #355

- lib/service/qualityfolio/package.sql.ts
- Add TAP Test Results table section to main dashboard with clickable drill-down navigation
- Create detailed TAP file view with individual test case analysis and pagination
- Implement URL encoding for TAP file names with spaces and special characters
- Add summary cards showing TAP file metrics (total tests, passed/failed counts, pass rates)
- Integrate tap_test_results and tap_test_results_detail database views for comprehensive data display
- Enhance table layouts with proper column ordering and visual status indicators
- Support sorting, searching, and pagination for efficient large dataset handling
This PR implements comprehensive TAP (Test Anything Protocol) test results integration into the QualityFolio web interface, providing users with powerful tools for monitoring, analyzing, …
> feat: implement comprehensive tap test results integration in qualityfolio #355

- lib/service/qualityfolio/stateless.sql
Added `html_test_execution_results` database view to QualityFolio for extracting structured test execution data from HTML test reports. This enables the dashboard to display meaningful test information from various HTML report formats.
- **Purpose**: Extract test execution data from HTML content stored in `uniform_resource` table
- **Scope**: Processes HTML files with test execution information
- **Output**: Structured data for QualityFolio dashboard integration
- `run_id` - Test run identifier (with HTML tag removal)
- `test_report_name` - Report title from HTML or filename
- `execution_title` - Test execution title from HTML headers
- `execution_status` - Test status (passed, failed, etc.)
- `start_time` - Test start timestamp (with fallback to file creation time)
- `end_time` - Test …
> feat: Add html_test_execution_results view for Qualityfolio HTML test report parsing #355

- lib/service/qualityfolio/qualityfolio-surveilr-prepare-service.ts
This PR introduces a new script `qualityfolio-surveilr-prepare-service.ts` for preparing Qualityfolio data using the surveilr command. The script provides a robust solution for data ingestion, database management, and environment validation.
- Environment and prerequisite validation
- Database backup and cleanup management
- Execution of surveilr ingest and shell commands
- Configuration handling through command-line arguments and environment variables
- Comprehensive error handling and logging
The script can be run using Deno with the following command:
```bash
deno run --allow-read --allow-write --allow-env --allow-run --allow-sys --allow-net qualityfolio-surveilr-prepare-service.ts [options]
> feat: add qualityfolio service preparation script #355

- lib/pattern/ai-context-middleware/README.md
- lib/pattern/ai-context-middleware/deps.ts
- lib/pattern/ai-context-middleware/package.sql.ts
- lib/pattern/ai-context-middleware/stateless.sql
introduces AI context middleware surveilr pattern, based on this [ticket](https://github.com/surveilr/www.surveilr.com/issues/556):
> feat: introduce ai context middleware surveilr pattern

- lib/pattern/ai-context-middleware/README.md
- lib/pattern/ai-context-middleware/package.sql.ts
- lib/pattern/ai-context-middleware/stateless.sql
Adds latest UI changes to the ai-context-engineering pattern
> fix: add new UI elements to pattern

- lib/pattern/compliance-explorer/package.sql.ts
**PR summary:**
This PR introduces placeholder cards for the TODO section in detail pages, providing a structured way to display upcoming tasks and prompts. 
Additionally, it adds control detail pages for HiTRUST and THSA, enabling users to view detailed compliance controls and related information.
> chore: Add placeholder TODO cards and control detail pages for HiTRUST and THSA #355

- lib/service/fleetfolio/eaa/Dockerfile
- lib/service/fleetfolio/eaa/env.sample
- lib/service/fleetfolio/eaa/fleetfolio-eaa-pentest-lite.runme.md
Merge main into feature branch
> Merge main into feature branch

- lib/pattern/compliance-explorer/package.sql.ts
Fixes to the compliance explorer SQLPage pattern for adding accordion to the HIPAA details page.
> fix: add accordion for hipaa policy, audit and author prompts

- lib/pattern/compliance-explorer/package.sql.ts
Fixed issue where pages were not loading/getting as expected.
Corrected breadcrumb links that were causing 404 errors.
> fix: resolve page loading issue and breadcrumb 404 links  #355

- lib/service/tem/custom_shell.ts
- lib/service/tem/package.sql.ts
- lib/service/tem/stateless.sql
extend tem_task_summary view with created_date, updated_date, and priority
> feat: extend tem_task_summary view with created_date, updated_date, and priority #586

- lib/service/tem/package.sql.ts
- lib/service/tem/stateless.sql
- created tem_wafw00f and tem_waf_hosts views to extract hosts and block content from wafw00f scans
- added sql page webui with breadcrumb, pagination, title, and description for wafw00f results
- ensured tenant and session context is included in the views and ui
> feat: add views and sql page webui for wafw00f results with tenant and session support #586

- lib/pattern/compliance-explorer/package.sql.ts
- lib/std/notebook/rssd.ts
- lib/std/notebook/sqlpage.ts
Add spry feature in compliance explorer
> Spry sql emit implementation
