surveilr/www.surveilr.com

lib/std/notebook/tap.ts
This pull request implements a change to enhance the idempotency of view management within the codebase. The primary change is the inclusion of the DROP VIEW IF EXISTS "${viewName}"; statement, which ensures that any attempts to drop a view do not result in errors if the view does not exist
=> fix: ensure idempotency by dropping view

lib/pattern/info-assurance-controls/README.md, lib/pattern/info-assurance-controls/tap.sql, lib/pattern/info-assurance-controls/tap.sql.ts, lib/pattern/info-assurance-policies/README.md, lib/pattern/info-assurance-policies/tap.sql, lib/pattern/info-assurance-policies/tap.sql.ts, lib/pattern/info-assurance/README.md, lib/pattern/info-assurance/tap.sql, lib/pattern/info-assurance/tap.sql.ts, lib/pattern/infra-assurance/README.md, lib/pattern/infra-assurance/tap.sql, lib/pattern/infra-assurance/tap.sql.ts, lib/pattern/infra-audit/README.md, lib/pattern/infra-audit/tap.sql, lib/pattern/infra-audit/tap.sql.ts
This pull request introduces the TAP (Test Anything Protocol) test integration into various assurance patterns to improve automated testing coverage and ensure the reliability of the infra and info assurance-related functionalities.
Added TAP tests for the following patterns:
- info-assurance
- info-assurance-controls
- info-assurance-policies
- infra-assurance
- infra-audit
=> feat: add tap test in infra and info assurance patterns #44

lib/pattern/direct-messaging-service/tap.sql.ts
=> chore: update unit test using tap #44

lib/pattern/content-assembler/README.md
This PR introduces a README file for the Content Assembler Pattern, providing a comprehensive guide to effectively understanding and using the pattern. The README covers the purpose, structure, and best practices for implementing the Content Assembler Pattern, making it easier for developers to integrate and customize content assembly within their applications.
=> docs: add readme of content assembler pattern #20

lib/pattern/content-assembler/README.md, lib/pattern/content-assembler/package.sql.ts, lib/pattern/content-assembler/package_sql_test.ts, lib/pattern/content-assembler/statefull.sql, lib/pattern/content-assembler/stateless.sql
This pull request introduces updates and enhancements across several SQL and test files to improve functionality, maintainability, and testing for stateful and stateless database operations.
=> Enhance SQL and Test Scripts for Stateful and Stateless Operations

lib/std/notebook/sqlpage.ts
This PR introduces the capability to apply a WHERE condition in the row count calculation of the pagination function. This enhancement allows for more refined data retrieval by filtering records based on specified conditions, improving the flexibility and efficiency of pagination when dealing with large datasets.
-  **Updated Pagination Function**: Added support for a whereSQL parameter in the pagination function configuration. The whereSQL parameter accepts an array of strings, where each string represents a field to be used in the WHERE clause.
- **Conditional SQL Generation**: Modified the countSQL query to include the `WHERE` clause only if `whereSQL` is specified and contains at least one field. This condition dynamically adds the `WHERE `clause and constructs the appropriate SQL …
=> feat: pagination count add where condition #20

lib/std/notebook/sqlpage.ts
This pull request updates the `where` parameter type in the SQL pagination function. Previously, `whereSQL` was expected as an array, but this update changes it to a string, allowing for more flexible and dynamic query composition.
**Code Change**: The `countSQL` query has been adjusted to handle `whereSQL` as a string:
```
const countSQL = config.countSQL
? config.countSQL
: this.SQL`SELECT COUNT(*) FROM ${config.tableOrViewName} ${
config.whereSQL && config.whereSQL.length > 0 ? config.whereSQL : ``
}`;
```
=> fix: pagination count add where condition #20

package.json, pnpm-lock.yaml
This pull request sets up Prettier as a code formatting tool for the project. Key changes include:
- Installed Prettier as a development dependency to ensure consistent formatting.
- Added a custom `npm run format` command to apply Prettier formatting to the codebase.
- Formatted existing files using the `npm run format` command.
This improves code consistency and maintainability by enforcing a standard formatting style throughout the project.
=> chore: implement code formatting with Prettier #136

lib/std/web-ui-content/shell.ts
The footer displayed outdated version details, which could cause confusion for users regarding the current version of Surveilr and its Web UI. This fix ensures consistency and clarity.
=> fix: footer surveilr version update #20

lib/std/web-ui-content/docs.ts
This PR fixes an issue with the bottom link in the functions-inner.sql file to ensure it points to the correct target.
=> fix: bottom link in function inner corrected #20

lib/pattern/content-assembler/README.md, lib/pattern/content-assembler/package.sql.ts
This PR addresses an issue with viewing uniform resource views in the console info schema. The problem caused incorrect or incomplete data representation, impacting the usability and debugging experience for the uniform resource views.
=> fix: console info schema uniform resource view issue #20

lib/std/web-ui-content/shell.ts
This PR addresses the issue where the `surveilr --version` command could not be used outside the Surveilr environment to determine the version. To resolve this, the version is now fetched directly from the `ur_ingest_session` table in the RSSD database using SQL.
1. **Version Retrieval Update**:  
- Replaced the `surveilr --version` command with an SQL query to fetch the version from the `ur_ingest_session` table:
```sql
SELECT json_extract(session_agent, '$.version') AS version 
FROM ur_ingest_session 
LIMIT 1;
```
- This ensures the correct version is retrieved in all environments.
2. **Improved Compatibility**:  
- Removed reliance on the `surveilr --version` command for external operations.
- Ensured that version fetching works seamlessly for both internal and external Surveilr …
=> fix: surveilr version issue #247

lib/service/qualityfolio/package.auto.sql, lib/std/web-ui-content/shell.ts
This PR refactors the version retrieval process by removing the Deno code previously used to fetch the Surveilr version using the surveilr --version command. The approach has been updated to use an SQL query to retrieve the version directly from the ur_ingest_session table in the RSSD database.
=> refactor: removed deno code for getting version #247

lib/std/package.sql.ts
This PR updates the SQL function to adjust the order of module initialization for the TypicalSqlPageNotebook.SQL method.
=> fix: change order of fucnction call

lib/service/diabetes-research-hub/study-specific-stateless/ctr-anderson-stateless.sql, lib/service/diabetes-research-hub/study-specific-stateless/detrended-stateless.sql, lib/service/diabetes-research-hub/study-specific-stateless/generate-cgm-combined-sql.ts, lib/service/diabetes-research-hub/study-specific-stateless/ieogc-ingest-data-sql.ts, lib/service/diabetes-research-hub/study-specific-stateless/ieogc-stateless.sql
- In **IEOGC**, **DFA**, and **CTR3** participant listings, update the study and participant identifiers when retrieving data from the `drh_participant` view.  
- Modify `file_meta_ingest_data` by changing `participant_sid` to `participant_display_id` for consistency.  
This ensures standardized participant identification across different datasets and aligns with the `drh_participant` view structure.
=> update: modify the participant and study identifiers #29

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateless.sql
Created views and SQL Page UI for the following system-related tables:
1. **system_user** – Stores information about system users.
2. **system_information** – Contains general system details such as hostname and architecture.
3. **system_server_uptime** – Tracks system uptime.
4. **system_ssh_keys_encrypted** – Manages SSH key encryption status.
5. **system_os_version** – Records OS version details.
=> feat: add views and SQL Page UI for system-related tables #355

lib/pattern/osquery-ms/queries.sql.ts
This PR updates the OSQuery query for retrieving process details by modifying how the pid (Process ID) is handled.
=> refactor : Update OSQuery Process Query - Modify pid Retrieval #355

lib/pattern/osquery-ms/queries.sql.ts
This PR adds an osquery query to retrieve Docker container port mappings. The query fetches private and public ports, along with container names, to provide better visibility into running container networking configurations.
=> feat : add docker container port query #355

lib/pattern/osquery-ms/queries.sql.ts
This PR enhances the container process visibility by including both user ID (uid) and process ID (pid) in the container process query. This allows improved user-level tracking of processes running within Docker containers, which is useful for auditing and security.
=> feat : add user id process id  in all container process query #355

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
This PR introduces support for rendering detailed AWS cost data within the FleetFolio UI by:
- Creating a new transformation table ur_transform_list_aws_cost_detail to parse JSON-based cost data from the uniform_resource table.
- Creating a view list_aws_cost_detail to abstract and simplify querying from the transformation table.
- Adding UI logic in fleetfolio/aws_cost_detail_list.sql to:
- Render breadcrumbs for navigation context
- Display a descriptive page title and summary
- Render a searchable and sortable cost summary table showing key cost metrics such as amortized and blended costs, region, and period
=> feat: add aws cost detail transformation table, view, and ui rendering logic #355

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql, lib/std/notebook/sqlpage.ts
This PR introduces support for retrieving and displaying AWS daily and monthly cost details. It enhances cost visibility by enabling analysis at multiple time granularities, which is essential for both operational monitoring and long-term budgeting.
=> feat: add aws daily and monthly cost detail #355

lib/pattern/compliance-explorer/package.sql.ts
This PR updates the visual branding assets for Compliance Explorer by replacing the existing logo and favicon with the new.
=> refactor: replace logo and favicon for compliance explorer #355

lib/pattern/osquery-ms/package.sql.ts
This PR updates the visual branding assets for osquery ms by replacing the existing logo and favicon with the new
=> refactor: replace logo and favicon for osquery ms #355

lib/pattern/osquery-ms/queries.sql.ts
This PR updates the osquery process query to include logic for checking and possibly filtering by process size (e.g., memory usage or file size). The change helps ensure that only relevant or significant processes are considered in downstream analysis.
=> feat: update process query to include size check #355

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
This PR adds support for multiple boundaries under the Assets section and ensures they are properly listed and displayed in Fleetfolio.
**Changes Made**
- Added logic to support multiple asset boundaries
- Updated Fleetfolio to display the new boundaries
- Ensured consistent integration between asset data and Fleetfolio UI
=> added multiple boundaries under assets and listed them in fleetfolio #25

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
This PR addresses minor text corrections and key renaming to improve consistency and accuracy in the codebase.
**Changes Made**
Corrected the casing of the caption from "FleetFolio" to "Fleetfolio".
**Renamed object keys for clarity and consistency:**
asset → assets
boundary → boundries
=> fix: correct caption casing and rename keys #355

lib/pattern/osquery-ms/queries.sql.ts
Removed the resident_size field from the container daemon info query to prevent unnecessary database size growth.
=> refactor: remove resident_size from container daemon info query to prevent db size growth #355

lib/pattern/osquery-ms/queries.sql.ts
This PR adds a new osquery query to monitor IDS PSAD logs. The query targets files under /var/log/psad* and /var/log/iptables.log to help detect and audit intrusion detection system (IDS) activity.
=> feat: add osquery query for IDS PSAD log monitoring #355

lib/pattern/osquery-ms/queries.sql.ts
This PR adds three new osquery queries focused on enhancing visibility into SSL/TLS and VPN configurations for Linux systems.
1. **SSL Certificate & Key File Check**
- Query: Osquery SSL Cert Files
- Purpose: Lists files under /etc/ssl/certs and /etc/ssl/private with metadata such as permissions, size, type, and ownership.
2. **SSL File Modification Monitoring**
- Query: Osquery SSL Cert File MTIME
- Purpose: Tracks mtime (last modification time) of certificate and key files to detect unexpected changes.
3. ***VPN Port Listening Detection**
- Query: Osquery VPN Listening Ports
- Purpose: Checks for services listening on common VPN ports (443, 1194, 500, 4500) to verify expected secure network setups.
=> feat: added queries to check ssl cert files, monitor cert mtime, and detect vpn-related listening ports on linux #355

lib/pattern/osquery-ms/queries.sql.ts
This PR adds new evidence collection queries to `queries.sql.ts` to support compliance controls CC6-0001 through CC6-0005. The updates include:
- **User and Admin Inventory** for processes across application, OS, DB, and network layers
- **Network Detail Queries** including listening ports, interface addresses, and full interface configuration
- **Security Group Mappings** via user-group relationships and admin role detection
- MySQL/PostgreSQL process inventory
- Cron jobs listing
- Interface details with full field selection
- Listening ports and network interface queries
- Process-to-user mappings by IT layer
- Admin user process queries
- OS-level admin user listing
- User to group membership mapping
These queries enhance audit readiness and support the Surveilr evidence collection …
=> feat: added osquery cells for user and admin inventory, network details, and security group mappings #355

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
- introduced a new tab on the host detail page to display ssl/tls listening status
- the view lists services listening on port 443 to help verify https/ssl configuration
- helpful for visibility, diagnostics, and compliance tracking
=> feat: added ssl/tls enabled tab to host detail page in fleetfolio #355

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
This PR introduces support in the Fleetfolio dashboard for displaying SSL certificate file metadata collected via osquery. It provides visibility into file attributes under `/etc/ssl/certs` and `/etc/ssl/private`, which are commonly used for storing TLS/SSL certificates and private keys.
- Integrates osquery results from the `file` table filtered by certificate-related paths.
- Displays detailed metadata such as:
- Path, directory, filename
- Inode, UID, GID
- File mode (permissions)
- Size, block size, hard links
- File type (e.g., directory or file)
- Enables compliance teams to validate correct permissions and secure storage of SSL assets.
- Added a table widget under the "Encryption & Certificates" section.
- Includes a helpful description above the table:
> **Description:**  
> This …
=> feat : add fleetfolio support for displaying SSL certificate file metadata using osquery #355

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
Added a new table view to the Fleetfolio dashboard: **SSL Certificate and Key File Modification Times**.
- Displays the `mtime` (modification time) of SSL certificate and key files located in `/etc/ssl/certs/` and `/etc/ssl/private/`.
- Helps in identifying unauthorized or unexpected modifications to SSL-related files.
- Implemented via Osquery with a Linux-only selector.
```sql
SELECT path, mtime FROM file WHERE path LIKE '/etc/ssl/certs%' OR path LIKE '/etc/ssl/private%';
=> feat: add ssl_certificate_and_key_file_modification_times table to fleetfolio dashboard #355

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
Added a new table to the Fleetfolio dashboard: **Osquery VPN Listening Ports**.
- Displays listening ports related to VPN services using Osquery.
- Ports filtered: 1194 (OpenVPN), 443 (HTTPS), 500 and 4500 (IPSec).
- Provides insights into network bindings for VPN-related services.
```sql
SELECT port, protocol, family, address, fd, socket, path, net_namespace 
FROM listening_ports 
WHERE port IN (1194, 443, 500, 4500);
=> feat: add osquery_vpn_listening_ports table to fleetfolio dashboard #355

lib/pattern/osquery-ms/queries.sql.ts
Commented out selected queries in the `queries.sql.ts` file to help reduce the size and growth rate of the local database.
- Certain queries were contributing significantly to DB bloat due to high-frequency or large result sets.
- Temporarily disabling them to improve performance and maintain manageable DB size.
- The affected queries are non-critical and can be re-enabled as needed.
- This change is aimed at improving stability and responsiveness of the Fleetfolio environment.
No logic or structure has been removed — only comments applied for safe rollback.
=> refactor: commented queries in queries.sql.ts to control db size growth #355

lib/pattern/osquery-ms/queries.sql.ts, lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
* Added support for **MySQL Process Inventory** in Fleetfolio:
* Extracts process name and binary path from osquery results.
* Creates a table `ur_transform_list_mysql_process_inventory` for dashboard consumption.
* Displays data in a tab titled `mysql_process_inventory` with a short description for context.
* Uncommented relevant queries in `queries.sql.ts` to restore expected functionality and ensure query execution during deployment.
* This helps track running MySQL services across Linux hosts and ensures query definitions are active for further data transformation.
=> add mysql process inventory query and uncomment queries in queries.sql.ts #355

lib/pattern/osquery-ms/queries.sql.ts
This PR modifies the `Osquery Interface Details Inventory` query by removing certain unused or redundant fields. The purpose of this change is to:
* Avoid duplication of interface metrics across hosts
* Reduce the volume of stored data
* Investigate and potentially improve the overall RSSD database size
This is part of ongoing efforts to optimize performance and storage efficiency in Fleetfolio.
=> refactor: reduce fields in 'Osquery Interface Details Inventory' to avoid duplication and check DB size #355

lib/service/fleetfolio/README.md, lib/service/fleetfolio/package.sql.ts
- Updated the Fleetfolio README with usage instructions for `deno fmt` and `deno lint` to help contributors maintain consistent code formatting and quality.
- Ran `deno fmt` on the codebase, resulting in minor formatting changes across existing files.
- Added a "Format Code" and "Lint Code" section in the README with example commands.
- Applied automatic formatting using `deno fmt`.
- Lint warnings related to unsupported `tsconfig.json` options (`baseUrl`, `paths`) are expected and can be safely ignored.
- No functional or logic changes were made—only documentation and formatting updates.
=> docs: add deno format/lint instructions to readme and apply formatting changes #355

lib/service/fleetfolio/package.sql.ts
**Overview**
We wanted to replace the static tab interface with a dynamic, searchable dropdown to improve discoverability and maintain the existing auto-submit behavior.
**Initial State**
* The form used a hard‑coded set of tabs for view selection.
* No search/filter capability; all 12 options were listed vertically.
**Changes Attempted**
1. Swapped `<ul>` tabs for a `<select>` element.
2. Tried native `<datalist>` for filtering—ran into inconsistent browser support.
3. Experimented with CSS flex and grid layouts for horizontal alignment.
4. Integrated TomSelect for a fully searchable dropdown widget.
**Technical Challenges**
* SQLPage’s form-rendering logic adds deep-nested wrappers, making CSS overrides tricky.
* TomSelect’s default inline styles conflicted with our grid setup, …
=> feat: convert tabs to searchable dropdown and enhance search functionality #355

lib/service/fleetfolio/package.sql.ts, lib/service/fleetfolio/stateful.sql, lib/service/fleetfolio/stateless.sql
- Added PostgreSQL Process Inventory as a new dropdown option in the host detail interface
- Implemented PostgreSQL process monitoring using osQuery
- Enabled pagination, search, and sorting for process data
- Integrated data source attribution and responsive UI components
=> feat: add PostgreSQL Process Inventory to host detail view #355

lib/service/qualityfolio/package.sql.ts
Updated the `<main>` element's class in qualityfolio to ensure the page body spans the full width of its container.
**Changes:**
Added w-full to the page-body class to fix layout issues where the page wasn't utilizing full available width.
*Old:*
`<main class="page-body container-xl flex-grow-1 px-md-5 px-sm-3 {{#if fixed_top_menu}}mt-5{{#unless (eq layout 'boxed')}} pt-5{{/unless}}{{else}} mt-3{{/if}}" id="sqlpage_main_wrapper">`
_New:_
`<main class="page-body w-full container-xl flex-grow-1 px-md-5 px-sm-3 {{#if fixed_top_menu}}mt-5{{#unless (eq layout 'boxed')}} pt-5{{/unless}}{{else}} mt-3{{/if}}" id="sqlpage_main_wrapper">`
**Reason:**
Adding w-full ensures consistent full-width behavior, resolving layout alignment issues observed in certain viewports.
=> fix: make page-body full width in qualityfolio #355

lib/service/qualityfolio/package.sql.ts
This PR simplifies the `<main>` tag layout in `qualityfolio` by reducing the number of utility classes and conditional Handlebars expressions.
- Removed `container-xl`, `px-md-5`, `px-sm-3`, and complex Handlebars conditionals related to spacing.
- Updated to a cleaner, more maintainable layout:
```html
<main class="page-body w-full flex-grow-1 px-0" id="sqlpage_main_wrapper">
=> refactor: simplify main layout container in qualityfolio #355

lib/service/qualityfolio/package.sql.ts
Implement individual test case accordions in group-detail.sql to mirror the accordion 
functionality from suite-data.sql. Replace the existing table with interactive accordion 
dropdowns that provide quick preview capabilities for test cases, including detailed 
information, execution statistics, and color-coded status indicators while preserving 
all existing functionality.
=> feat: replace test case table with accordion dropdowns in group-detail.sql #355

lib/service/qualityfolio/package.sql.ts
This PR addresses the following issues in the TAP Test Results and HTML Test Execution Results:
1. **'Mixed' Status Field Issue:**
- The status field in the results was showing a value of 'Mixed' when multiple statuses were present, leading to confusion.
- **Solution:** Removed the 'status' field from both the TAP Test Results and HTML Test Execution Results to improve clarity and prevent the misleading 'Mixed' status.
2. **Test Case Count Mismatch:**
- There was a mismatch between the displayed test case count and the actual number of test cases due to the use of the `DISTINCT` keyword in the count query.
- **Solution:** Removed the `DISTINCT` clause from the count query to correctly calculate the total number of test cases.
- Enhanced clarity of the test results by removing the …
=> fix: remove 'mixed' status field and resolve test case count mismatch #355

lib/std/notebook/sqlpage.ts
This PR removes extraneous or unintended text that was being displayed as part of the pagination component across QualityFolio pages. The fix improves the visual clarity and user experience by ensuring only relevant pagination elements are shown.
=> fix: remove unwanted text from pagination component #355

lib/service/fleetfolio/package.sql.ts, lib/service/qualityfolio/package.sql.ts
This PR introduces the following enhancements to improve usability and consistency across the platforms:
**Qualityfolio:**
TAP test result values are now ordered in ascending order based on the title field, improving readability and making result interpretation easier.
**Fleetfolio:**
Updated the UI to display all available options, ensuring comprehensive visibility and access for users during configuration or selection processes.
=> fix: sort TAP results by title in qualityfolio and show all options in fleetfolio #355

lib/service/qualityfolio/stateless.sql
**Problem:**
There was a mismatch between the total test case count displayed and the number of test cases shown in the TAP Results table in Qualityfolio. This led to confusion when reviewing test outcomes.
**Fix Implemented:**
1. Aligned the total test case count with the actual number of test cases rendered in the TAP Results table.
1. Ensured consistency between backend aggregation and frontend display logic.
=> fix: resolve mismatch between total TAP test case count and displayed table entries #355

lib/service/qualityfolio/package.sql.ts, lib/service/qualityfolio/stateless.sql
Refactored and corrected the logic for extracting the execution_title from HTML content in test result documents.
**Changes Made:**
Renamed previous execution_title logic to execution_id, preserving the original logic that parsed `<h1> or <h2>` tags containing “test” or “execution”.
Introduced a new execution_title field that accurately extracts the title from `<p><b>Title:</b> ...</p> `HTML tags.
Improved robustness of the substring extraction with fallback length limits and conditional parsing logic.
This change separates the logic of identifying an execution ID (from headers) and an explicit execution title (from <p><b>Title:</b>), improving accuracy in representing test execution metadata.
=> fix: correct extraction of execution title from html content #355

lib/service/tem/README.md, lib/service/tem/custom_shell.ts, lib/service/tem/deps.ts, lib/service/tem/package.sql.ts, lib/service/tem/stateless.sql
This update enhances the TEM (Threat Exposure Management) SQLPage by adding support for displaying web scan and DNS enumeration results from WhatWeb and dnsx.
- Added a generalized schema for WhatWeb results including URL, status code, IP address, country, server software, detected technologies, and key HTTP headers.
- Added a generalized schema for dnsx results including domain, status code, resolver, IP address, DNS status, TTL, and timestamp.
- Introduced standardized titles and page descriptions:
- **Web Technology Fingerprinting Results** for WhatWeb
- **DNS Enumeration Results** for dnsx
- Ensured output pages are consistent, minimal, and reusable across different scans.
This enables security teams to:
- View reconnaissance data in a structured format.
- Perform quick assessments of …
=> feat: integrate whatweb and dnsx scan result pages with generalized schema and descriptions #586

lib/service/tem/package.sql.ts, lib/service/tem/stateless.sql
Integrated Nuclei vulnerability scanner results into TEM by creating a dedicated SQL view (`list_nuclei_data`). This enables displaying scan findings with key metadata including host, URL, template ID, severity, and timestamp.
- Added SQL view to extract and normalize Nuclei JSONL results.
- Mapped key fields: host, URL, template ID, finding name, description, severity, IP, matched path, and scan timestamp.
- Prepared user-friendly column titles for table display.
This enhancement provides better visibility into detected exposures and vulnerabilities, aligning Nuclei results with the existing TEM reporting structure.
=> add Nuclei scan results integration with structured sql view #586

lib/pattern/compliance-explorer/package.sql.ts
This PR introduces the following enhancements to the Compliance Controls module:
1. **CMMC Control Detail Pages**  
- Added detail pages for CMMC Level 1, 2, and 3 controls.  
- Properly render multi-line CMMC codes as clickable links.  
- Display control question, description, SCF domain, SCF control, and SCF IDs (FII IDs) on the detail page.  
2. **HIPAA Control Detail Pages**  
- Added detail pages for HIPAA Security Rule controls.  
- Display full control information including question, description, domain, and control mappings.
3. **Listing Page Pagination**  
- Added pagination for CMMC control listing pages using SQLPage’s built-in pagination helper.  
- Supports `$limit` and `$offset` automatically, with pagination controls rendered at top and bottom.  
4. **Breadcrumb …
=> chore: add CMMC and HIPAA control detail pages

lib/service/tem/package.sql.ts, lib/service/tem/stateless.sql
This PR updates the UI for session and tenant pages and introduces a new findings page:
* **Session & Tenant Pages**
* Replaced the previous card-based view with a **table listing**.
* Each session now displays details such as session time, number of analysis tools executed, start and end dates, agent, and version.
* Improved readability and sorting for better tracking of sessions.
* **Findings Page**
* Added a new findings page under each session and tenant.
* Displays results from multiple scanning and reconnaissance tools (e.g., What web data, DNSX, Nuclei, Naabu, Subfinder, HTTPX, Nmap).
* Each finding is mapped with **session name** and **count of results**.
* Provides consolidated insights for easier exposure analysis.
Screenshots attached show:
* **Attack Surface Mapping by …
=> feat: changed session and tenant pages from card view to table listing #586

lib/pattern/compliance-explorer/package.sql.ts
**Summary**
This PR introduces control detail pages for AICPA SOC 2 Type I, SOC 2 Type II, and ISO 27001 v3. Each regime now has dedicated detail views with breadcrumbs, metadata, and TODO placeholder cards, providing a consistent browsing experience across frameworks.
**Changes Made**
* Added `soc2_type1_detail.sql`, `soc2_type2_detail.sql`, and `iso-27001_detail.sql`
* Added listing integration for the above regimes
* Cleaned up table listings by removing unnecessary columns
* Ensured consistent pagination, sorting, and search functionality across all control listings
=> chore: add control detail pages for AICPA and ISO 27001

lib/service/tem/package.sql.ts
Added a custom SQLPage shell template (`shell-custom.handlebars`) to the **tem** package (`package.sql.ts`).
* Introduced `@spn.shell` configuration with the following options:
* `breadcrumbsFromNavStmts: "no"`
* `shellStmts: "do-not-include"`
* `pageTitleFromNavStmts: "no"`
* Defined a custom HTML structure with:
* Base CSS inclusion (`sqlpage.css` + dynamic CSS from `css` array).
* Font handling with support for both local fonts and Google Fonts.
* JavaScript setup (`sqlpage.js`, additional JS, and module scripts).
* Configurable `<body>` layout (boxed or fluid) with theme support.
* Page wrapper and main content structure bound to SQLPage row rendering.
This change allows the **tem** module to use a customized SQLPage shell template, giving more flexibility for styling, fonts, and …
=> feat: add custom shell template #586

lib/pattern/compliance-explorer/stateful.sql, lib/pattern/compliance-explorer/stateless.sql
---
* Added new SQL views for compliance controls (CMMC, HIPAA, HITRUST, ISO27001, SOC2) to enable detailed control exploration in Compliance Explorer.
* Each view includes control identifiers, codes, questions, evidence fields, and display order for structured retrieval.
* Updated compliance regime table to include additional fields and sample data to support expanded compliance frameworks.
---
=> chore: add views for CMMC, HIPAA, HITRUST, ISO27001, SOC2 controls

lib/service/qualityfolio/eg.surveilr.com-prepare.ts
Body Spawn the package.sql generator from eg.surveilr.com-prepare.ts using Deno.Command so generation runs asynchronously and pipes stdout directly into the rssd store file. Replace deprecated Deno.run usage, pipe child stdout/stderr to appropriate destinations, and avoid double-closing the output file (fixes BadResource errors). Add logging around the spawn to help debugging.
- Use Deno.Command to run deno run -A ./package.sql.ts and pipe stdout -> rssd/package.sql.
- Pipe child's stderr to parent stderr so errors are visible.
- Avoid closing the file while pipeTo owns the writable (removed redundant close that caused BadResource).
- Keep main ingest flow non-blocking; child's status is not awaited by default.
=> feat: spawn package.sql generator as background process and fix resource handling #654
